### PR TITLE
Add Fortran to Languages.md and add Types

### PR DESCRIPTION
**Pull request by deavmi**

### CODE REVIEW

**Comment by Walkman100** [comment]
What is Generic? And is fortran really a "static" language?

**Comment by deavmi** [comment]
By Generic I mean it is not OOP nor functional. Just plain.

**Comment by deavmi** [comment]
By static you mean? Newer fortran supports OOP but fortran is mainly a generic language. I haven't tried OOP in fortran.

**Comment by deavmi** [comment]
Oh. You mean statically typed. Yes it it statically typed and so is Java and C and C++.

**Comment by deavmi** [comment]
and Visual Basic.

**Comment by Walkman100** [comment]
> Oh. You mean statically typed. Yes it it statically typed and so is Java and C and C++.

no man, like HTML and CSS aren't actually programming languages, I just called that Static, and you put Fortran under the same category...

**Comment by Walkman100** [comment]
> By Generic I mean it is not OOP nor functional. Just plain.

then you should leave the field blank.

**Comment by deavmi** [comment]
Okay. I see that point but I feel like it should say Generic. Just to be clear.

**Comment by Walkman100** [comment]
Is Fortran Static like HTML and CSS?
In case you missed it:

> no man, like HTML and CSS aren't actually programming languages, I just called that Static, and you put Fortran under the same category...

Also, to show you what the document looks like pre-processed:
https://raw.githubusercontent.com/Walkman100/gists/master/Languages.md
Compared to the file from this PR:
https://raw.githubusercontent.com/Walkman100/gists/941c5723fa18fe2ac8fba8ae7de08c09ad9a7c5d/Languages.md
Your Fortran entry is mangled

**Comment by deavmi** [comment]
Lol. K. :smile:

**Comment by Walkman100** [comment]
> Is Fortran Static like HTML and CSS?

**Comment by deavmi** [comment]
No

**Comment by Walkman100** [comment]
Eugh finally I pry the answer from deavmi

**Comment by deavmi** [comment]
Pry meaning to retrieve or get?

**Comment by Walkman100** [comment]
yes, with difficulty

**Comment by Walkman100** [comment]
and slowly

**Comment by deavmi** [comment]
So like it was a long painful endurance to get the answer type thing. :) I see. :) thanks

**Pull request merged**
